/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f5',
        'surface-dim': '#dbdad6',
        'surface-bright': '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ef',
        'surface-container': '#efeeea',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#504441',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f0ed',
        outline: '#827470',
        'outline-variant': '#d4c3be',
        'surface-tint': '#77574d',
        primary: '#442a22',
        'on-primary': '#ffffff',
        'primary-container': '#5d4037',
        'on-primary-container': '#d4ada1',
        'inverse-primary': '#e7bdb1',
        secondary: '#1b6d24',
        'on-secondary': '#ffffff',
        'secondary-container': '#a0f399',
        'on-secondary-container': '#217128',
        tertiary: '#432c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#604100',
        'on-tertiary-container': '#efa800',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#e7bdb1',
        'on-primary-fixed': '#2c160e',
        'on-primary-fixed-variant': '#5d4037',
        'secondary-fixed': '#a3f69c',
        'secondary-fixed-dim': '#88d982',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005312',
        'tertiary-fixed': '#ffdeac',
        'tertiary-fixed-dim': '#ffba38',
        'on-tertiary-fixed': '#281900',
        'on-tertiary-fixed-variant': '#604100',
        background: '#fbf9f5',
        'on-background': '#1b1c1a',
        'surface-variant': '#e4e2de',
        
        // Custom Surface strategy colors from brief
        'cream-warm': '#FDFBF7',
        'slate-clean': '#F1F5F9',
      },
      fontFamily: {
        'playfair': ['"Playfair Display"', 'serif'],
        'inter': ['Inter', 'sans-serif'],
        'plex': ['"IBM Plex Sans"', 'sans-serif'],
        'mono': ['"Space Mono"', 'monospace'],
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem', // 4px
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'soft-arch': '32px', // 32px
        'full': '9999px',
      },
      spacing: {
        'base': '8px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      }
    },
  },
  plugins: [],
}
